models/Snippet.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%snippet}}".
 *
 * @property integer $id
 * @property string $title
 * @property string $code
 * @property string $description
 *
 * @property TagSnippet[] $tagSnippets
 * @property Tag[] $tags
 */
class Snippet extends \yii\db\ActiveRecord {

    public $pre_tags;

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return '{{%snippet}}';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['title', 'code', 'pre_tags','language'], 'required'],
            [['code', 'description'], 'string'],
            [['title'], 'string', 'max' => 255],
            [['pre_tags'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'pre_tags' => Yii::t('app', 'Tags'),
            'code' => 'Code',
            'description' => 'Description',
            'language' => 'Language',
        ];
    }

    public function afterSave($insert, $changedAttributes) {


        $tags = explode(",", $this->pre_tags);

        if(!$insert) {
            foreach($this->tagSnippets as $tag) {
                $tag->delete();
            }
        }

        foreach ($tags as $tag) {
            $model = Tag::findOne(['title' => $tag]);
            if ($model === NULL) {
                $model = new Tag();
                $model->attributes = ['title' => $tag];
                $model->save();
            }
            $relation = new TagSnippet();
            $relation->attributes = [
                'snippet_id' => $this->id,
                'tag_id' => $model->id
            ];

            $relation->save();
        }

        return parent::afterSave($insert, $changedAttributes);
    }

    public function beforeDelete() {

        if ($this->tagSnippets) {
            foreach ($this->tagSnippets as $tagSnippets) {
                $tagSnippets->delete();
            }
        }

        return parent::beforeDelete();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTagSnippets() {
        return $this->hasMany(TagSnippet::className(), ['snippet_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTags() {
        return $this->hasMany(Tag::className(), ['id' => 'tag_id'])->viaTable('{{%tag_snippet}}', ['snippet_id' => 'id']);
    }

    public function getTagArray() {
        $data = [];
        if ($this->tags) {
            
            foreach ($this->tags as $tags) {
                $data[] = $tags->title;
            }
        }

        return $data;
    }
    
    public function getTagString() {
        if($this->tagArray) {
            return implode(",", $this->tagArray);
        }

        return "";
    }

}

models/SnippetType.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tbl_snippet_type".
 *
 * @property integer $id
 * @property string $title
 * @property string $mode
 */
class SnippetType extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_snippet_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'mode'], 'required'],
            [['mode'], 'string'],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'mode' => 'Mode',
        ];
    }
}

controllers/SnippetController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\models\Snippet;
use app\models\SnippetType;
use app\models\search\SnippetSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SnippetController implements the CRUD actions for Snippet model.
 */
class SnippetController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['search', 'index', 'view', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['create', 'update', 'delete', 'index', 'view', 'search'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['search', 'index', 'view'],
                        'roles' => ['?'],
                    ],
                    
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionSearch()
    {
        $q = Yii::$app->request->post('q');

        if(!$q) $this->redirect(['site/index']);

        $searchModel = new SnippetSearch();
        $dataProvider = $searchModel->indexSearch($q);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Snippet models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SnippetSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    /**
     * Displays a single Snippet model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->redirect(['update', 'id' => $id]);
    }

    /**
     * Creates a new Snippet model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Snippet();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            $model->language = "text";
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Snippet model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $model->pre_tags = $model->getTagString();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Snippet model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionCheckMode()
    {
        $pre_tags = Yii::$app->request->post('pre_tags');
        $pre_tags = explode(",", $pre_tags);

        $result = [];

        foreach($pre_tags as $tag) {
            $model = SnippetType::find()->where('mode = :tag OR title = :tag', [':tag' => trim($tag)])->one();
            if($model) {
                $result['mode'] = $model->mode;
                break;
            }
        }

        header('Content-Type: application/json');
        echo json_encode($result);

    }

    /**
     * Finds the Snippet model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Snippet the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Snippet::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/snippet/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
?>

<div class="snippet-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'pre_tags')->textInput(['maxlength' => false]) ?>

    <?= Html::label("language:" . Html::activeDropDownList($model, 'language',ArrayHelper::map(app\models\UserConfig::getModes(), 'mode','mode')), "", ['class' => 'pull-right', 'id' => 'detected_language'])?>
    
    <?=
    $form->field($model, 'code')->widget(
        'trntv\aceeditor\AceEditor',
        [
            'name' => 'aceeditor_w1',
            'mode'=> 'sh', // programing language mode. Default "html"
            'theme'=>'monokai' // editor theme. Default "github"
        ]
    )
    ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Add' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

    <?php
    $script = "
    function editor_setMode(mode) {
        aceeditor_w1.getSession().setMode('ace/mode/' + mode)
    }

    var changed = false;
    $('#snippet-pre_tags').on('change', function(){
       
       if(changed == false) {
             firstTag = $(this).val().split(',');
             $.ajax({
               type: 'POST',
               url: '". Url::toRoute(['snippet/check-mode']) ."',
               data: { pre_tags: firstTag[0] },
               dataType: 'json',
               success: function(data) {
                  if(data && data.mode) {
                      $('#snippet-language').val(data.mode)
                      changed = true;
                      editor_setMode(data.mode)
                  }   
               }
                  
            });
       }
    });

    $('#snippet-language').on('change', function(){
        val = $(this).val();
        editor_setMode(val)
        changed = true;
    });
    ";

    $this->registerJs($script, $this::POS_READY);
    ?>

</div>

views/snippet/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\SnippetSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="snippet-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'code') ?>

    <?= $form->field($model, 'description') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/snippet/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Snippet */

$this->title = 'New Snippet';
$this->params['breadcrumbs'][] = ['label' => 'Snippets', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="snippet-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/snippet/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\BaseStringHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Snippets';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="snippet-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('New Snippet', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'rowOptions'   => function ($model, $key, $index, $grid) {
            return ['data-id' => $model->id, 'class' => "link-simulation"];
        },
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'pre_tags',
                'value' => 'tagString',
            ],
            'title',
//            [
//                'attribute' => 'code',
//                'value' => BaseStringHelper::truncate('id', 5)
//            ],
//            'description:ntext',

            // [
            //     'class' => 'yii\grid\ActionColumn',
            //     'template'=>'{view}'
            // ],
        ],
    ]); ?>

</div>

<?php
$this->registerCss("

    .link-simulation {
        cursor: pointer !important
    }

    .link-simulation:hover {
        background: #BDCBD9 !important;
    }

");
$this->registerJs("

    $('td').click(function (e) {
        var id = $(this).closest('tr').data('id');
        if(e.target == this)
            location.href = '" . Url::to(['snippet/view']) . "?id=' + id;
    });

");

views/snippet/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Snippet */

$this->title = 'Snippet ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Snippets', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="snippet-update">

    <h1><?= Html::encode($model->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/snippet/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Snippet */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Snippets', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="snippet-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('New', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            [
                'attribute' => 'pre_tags',
                'value' => implode(",", $model->tagArray)
            ],
            'code:ntext',
            'description:ntext',
        ],
    ]) ?>

</div>